export const GET_BASE_COLLECTION_PENDING = 'GET_BASE_COLLECTION_PENDING'
export const GET_BASE_COLLECTION_ERROR = 'GET_BASE_COLLECTION_ERROR'
export const GET_BASE_COLLECTION_SUCCESS = 'GET_BASE_COLLECTION_SUCCESS'
